server:
  port: 8080

datasource1:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  url: jdbc:mysql://localhost:3306/spring_project
  driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback-spring-local.xml
  level:
    org:
      hibernate:
        SQL: DEBUG